import {
  IsEmail,
  IsString,
  MinLength,
  IsOptional,
  Matches,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class RegisterDto {
  @ApiProperty({
    description: 'User email address for authentication and notifications',
    example: 'user@example.com',
  })
  @IsEmail()
  email!: string;

  @ApiProperty({
    description: 'Unique username for public identification (min 3 characters)',
    example: 'stellar_developer',
    minLength: 3,
  })
  @IsString()
  @MinLength(3)
  username!: string;

  @ApiProperty({
    description: 'Secure password for account authentication (min 8 characters)',
    example: 'SecurePass123!',
    minLength: 8,
  })
  @IsString()
  @MinLength(8)
  password!: string;

  @ApiProperty({
    description: 'User first name for profile display',
    example: 'John',
  })
  @IsString()
  firstName!: string;

  @ApiProperty({
    description: 'User last name for profile display',
    example: 'Doe',
  })
  @IsString()
  lastName!: string;

  @ApiPropertyOptional({
    description:
      'Ethereum wallet address for Web3 authentication (format: 0x followed by 40 hex characters)',
    example: '0x742d35Cc6634C0532925a3b844Bc9e7595f1e2f0',
  })
  @IsOptional()
  @Matches(/^0x[a-fA-F0-9]{40}$/, {
    message: 'walletAddress must be a valid Ethereum address',
  })
  walletAddress?: string;
}

export class LoginDto {
  @ApiProperty({
    description: 'Registered email address',
    example: 'user@example.com',
  })
  @IsEmail()
  email!: string;

  @ApiProperty({
    description: 'Account password',
    example: 'SecurePass123!',
  })
  @IsString()
  password!: string;
}

export class WalletAuthDto {
  @ApiProperty({
    description:
      'Ethereum wallet address for Web3 authentication (format: 0x followed by 40 hex characters)',
    example: '0x742d35Cc6634C0532925a3b844Bc9e7595f1e2f0',
  })
  @Matches(/^0x[a-fA-F0-9]{40}$/, {
    message: 'walletAddress must be a valid Ethereum address',
  })
  walletAddress!: string;

  @ApiProperty({
    description:
      'Message that was signed by the wallet (typically a nonce or challenge string)',
    example: 'Sign this message to authenticate: abc123',
  })
  @IsString()
  message!: string;

  @ApiProperty({
    description:
      'Cryptographic signature generated by signing the message with the wallet private key',
    example:
      '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef12',
  })
  @IsString()
  signature!: string;
}

export class RefreshTokenDto {
  @ApiProperty({
    description: 'Refresh token received from login or registration',
    example:
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c',
  })
  @IsString()
  refreshToken!: string;
}

export class UserResponseDto {
  @ApiProperty({ description: 'Unique user identifier', example: 'ck1234567890' })
  id!: string;
  
  @ApiProperty({ description: 'User email address', example: 'user@example.com' })
  email!: string;
  
  @ApiProperty({ description: 'User username', example: 'stellar_developer' })
  username!: string;
  
  @ApiPropertyOptional({
    description: 'Ethereum wallet address',
    example: '0x742d35Cc6634C0532925a3b844Bc9e7595f1e2f0',
  })
  walletAddress?: string;
}

export class AuthResponseDto {
  @ApiProperty({
    description: 'JWT access token for API authentication (expires in 15 minutes)',
    example:
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c',
  })
  accessToken!: string;

  @ApiProperty({
    description: 'JWT refresh token for obtaining new access tokens (expires in 7 days)',
    example:
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c',
  })
  refreshToken!: string;

  @ApiProperty({
    description: 'Authenticated user information',
    type: UserResponseDto,
  })
  user!: UserResponseDto;
}
